export const XSD = {
    anyURI: "http://www.w3.org/2001/XMLSchema#anyURI",
    base64Binary: "http://www.w3.org/2001/XMLSchema#base64Binary",
    boolean: "http://www.w3.org/2001/XMLSchema#boolean",
    byte: "http://www.w3.org/2001/XMLSchema#byte",
    date: "http://www.w3.org/2001/XMLSchema#date",
    dateTime: "http://www.w3.org/2001/XMLSchema#dateTime",
    decimal: "http://www.w3.org/2001/XMLSchema#decimal",
    double: "http://www.w3.org/2001/XMLSchema#double",
    float: "http://www.w3.org/2001/XMLSchema#float",
    hexBinary: "http://www.w3.org/2001/XMLSchema#hexBinary",
    int: "http://www.w3.org/2001/XMLSchema#int",
    integer: "http://www.w3.org/2001/XMLSchema#integer",
    long: "http://www.w3.org/2001/XMLSchema#long",
    negativeInteger: "http://www.w3.org/2001/XMLSchema#negativeInteger",
    nonNegativeInteger: "http://www.w3.org/2001/XMLSchema#nonNegativeInteger",
    nonPositiveInteger: "http://www.w3.org/2001/XMLSchema#nonPositiveInteger",
    positiveInteger: "http://www.w3.org/2001/XMLSchema#positiveInteger",
    short: "http://www.w3.org/2001/XMLSchema#short",
    string: "http://www.w3.org/2001/XMLSchema#string",
    unsignedByte: "http://www.w3.org/2001/XMLSchema#unsignedByte",
    unsignedInt: "http://www.w3.org/2001/XMLSchema#unsignedInt",
    unsignedLong: "http://www.w3.org/2001/XMLSchema#unsignedLong",
    unsignedShort: "http://www.w3.org/2001/XMLSchema#unsignedShort",
} as const